name: 'BlueBuild'
description: 'Build a custom OS image'
inputs:
  recipe:
    description: |
      The [recipe](https://blue-build.org/reference/recipe/) file to build the image from, relative to the `config/` directory.
    required: true
    default: 'recipe.yml'
  cosign_private_key:
    description: |
      The Sigstore/cosign secret used to sign the image.

      Example: `&#36;{{ secrets.SIGNING_SECRET }}`
    required: true
  registry_token:
    description: | 
      The token used to sign into the container registry.

      Example: `&#36;{{ github.token }}`
    required: true
  pr_event_number:
    description: |
      The event number used to tag images pushed from pull requests.

      Example: `&#36;{{ github.event.number }}`
    required: true
  maximize_build_space:
    description: |
      Whether to run the unwanted software remover to maximize build space in the GitHub builder.
      Use this if your builds are taking too much space.
      Input must match the string 'true' for the step to be enabled.
    required: false
    default: 'false'
  registry:
    description: |
      The container registry to push the built image to.
    required: false
    default: 'ghcr.io'
  registry_namespace:
    description: |
     The namespace on the registry to push to.
     
     Example: `ublue-os`
    required: false
    default: ${{ github.repository_owner }}
runs:
  using: "composite"
  steps:
    # building custom images might take a lot of space, 
    # so it's best to remove unneeded softawre
    - name: Maximize build space
      uses: ublue-os/remove-unwanted-software@v6
      if: ${{ inputs.maximize_build_space == 'true' }}

    # clones user's repo
    - uses: actions/checkout@v4

    # deps used by cli to build & inspect imaegs
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y podman

    # blue-build/cli does the heavy lifting
    - name: Build Image
      shell: bash
      env:
        COSIGN_PRIVATE_KEY: ${{ inputs.cosign_private_key }}
        GH_TOKEN: ${{ inputs.registry_token }}
        GH_PR_EVENT_NUMBER: ${{ inputs.pr_event_number }}
      run: |
        podman run \
          -v buildah-vol:/var/run/containerd \
          -v $PWD:/bluebuild \
          --env-host \
          --network=host \
          --privileged \
          --device /dev/fuse \
          ghcr.io/blue-build/cli:v0.8.0-alpine \
          build -vv --push ./config/${{ inputs.recipe }} \
          --registry ${{inputs.registry}} \
          --registry-namespace ${{inputs.registry_namespace}}
