name: 'BlueBuild'
description: 'Build a custom OS image'
inputs:
  recipe:
    description: 'recipe.yml file to build'
    required: true
    default: 'recipe.yml'
  registry:
    description: 'container registry to push image to (default: ghcr.io)'
    required: false
    default: 'ghcr.io'
  registry_namespace:
    description: 'namespace on registry to push to (example: ublue-os)'
    required: false
    default: ${{github.repository_owner}}
  cosign_private_key:
    description: 'secret used to sign final image'
    required: false
  registry_token:
    description: 'token used to sign into registry'
    required: true
  pr_event_number:
    description: 'event number'
    required: true
runs:
  using: "composite"
  steps:
    # building custom images might take a lot of space, 
    # so it's best to remove unneeded softawre
    - name: Maximize build space
      uses: ublue-os/remove-unwanted-software@v6

    # clones user's repo
    - uses: actions/checkout@v4

    # deps used by cli to build & inspect imaegs
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y podman

    # blue-build/cli does the heavy lifting
    - name: Build Image
      shell: bash
      env:
        COSIGN_PRIVATE_KEY: ${{ inputs.cosign_private_key }}
        GH_TOKEN: ${{ inputs.registry_token }}
        GH_PR_EVENT_NUMBER: ${{ inputs.pr_event_number }}
      run: |
        podman run \
          -v buildah-vol:/var/run/containerd \
          -v $PWD:/bluebuild \
          --env-host \
          --network=host \
          --privileged \
          --device /dev/fuse \
          ghcr.io/blue-build/cli:main-alpine \
          build -vv --push ./config/${{ inputs.recipe }} \
          --registry ${{inputs.registry}} \
          --registry-namespace ${{inputs.registry_namespace}}
